name: unskool CI

on:
  push:
    branches:
      - master
jobs:
  build:
    name: build_apk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the cod    
      uses: actions/checkout@master
      with:
        ref: master
    - name: test script
      run: |
        a=1
        if [  $a -eq 1 ]
        then
          echo "success"
        else
          echo "fail"
        fi
    - name: Greetings
      uses: ./.github/actions/hello-world
    - name: Build debug apk
      run: ./android/gradlew build   

      https://github.com/arjunoo7/android-/blob/master/gradlew