name: unskool CI

on:
  push:
    branches:
      - master
jobs:
  build:
    name: build_apk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the cod    
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch        
    - name: test script
      run: |
        a=1
        if [  $a -eq 1 ]
        then
          echo "success"
        else
          echo "fail"
        fi
        echo $BRANCH_NAME
    - name: Greetings
      uses: ./.github/actions/hello-world
    - name: Build debug apk
      run: ./android/gradlew build   

      #https://github.com/arjunoo7/android-/blob/master/gradlew