name: unskool CI

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build_apk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the cod    
      uses: actions/checkout@v2
      with:
        ref: test-actions
    - name: check files
      run: ls .github/
    - name: Greets user
      uses: actions/hello-world
    - name: Build debug apk
      run: ./android/gradlew build   