name: unskool CI

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build_apk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the cod    
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Greets user
      uses: ./.github/actions/hello-world/action.yaml
    - name: Build debug apk
      run: ./android/gradlew build   