name: unskool CI

on:
  push:
    branches:
      - master
jobs:
  build:
    name: build_apk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the cod    
      uses: actions/checkout@v2
      with:
        ref: master
    - name: check files
      run: | 
        ls -la
    - name: Greets user
      run: echo "hi"
    -  uses: /.github/actions/hello-world
    - name: Build debug apk
      run: ./android/gradlew build   